source 'https://rubygems.org'

# Uncomment it if you are going to use 'webkit' driver. QT library should be installed. See https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit
#
# gem 'capybara-webkit'

# gem 'howitzer', github: 'strongqa/howitzer', branch: 'v2.0'
# Uncomment it if you are going to use 'testingbot' service. See It's web-site: https://testingbot.com
# gem 'testingbot'
# Uncomment it if you are going to use 'poltergeist' driver. PhantomJS should be installed. See https://github.com/jnicklas/capybara#poltergeist
# gem 'poltergeist'
gem 'howitzer'
gem 'rest-client', '~> 1.8'
gem 'repeater'
gem 'capybara'
gem 'rspec'
gem 'byebug'
gem 'gmail'
gem 'mail'
gem 'faker'
gem 'factory_girl'
gem 'site_prism'
