###########################################################
#  COMMON SETTINGS                                        #
###########################################################
 debug_mode: false
 app_host: https://www.google.com/accounts/?hl=en
 maximized_window: true
 driver: selenium
 sel_browser: chrome
###########################################################
# LOGGER SETTINGS                                         #
###########################################################
 log_dir: "log"
 txt_log: log.txt
 html_log: log.html
 selenium_server_log: selenium-server.log
 required_clean_logs: true
 rawler_log: rawler_log.txt
 add_rawler_xml_log: false
 rawler_xml_log: rawler_log.xml
 add_rawler_html_log: false # not implemented yet
 rawler_html_log: rawler_log.html # not implemented yet

###########################################################
# MAILGUN SETTINGS                                        #
###########################################################
# mailgun_key: mailgun_account_private_key
# mailgun_domain: mailgun_domain_with_stored_method

############################################################
# TIMEOUTS                                                 #
############################################################
 timeout_tiny: 1
 timeout_short: 3
 timeout_small: 20
 timeout_medium: 60